### ISSUE TITLE
Unable to Load JPEG Textures from cmd.exe

### ISSUE THREAD

**Issue by DavidMansolino** [omichel/webots#137] opened 2019-01-25 07:49 UTC
**Describe the Bug**
JPEG textures doesn't load and produce the following error message:
```
WARNING: Texture image size of 'C:/Program Files/Webots/projects/objects/obstacles/protos/textures/oil_barrel_bottom_occlusion.jpg' is not a power of two: rescaling it from -1x-1 to 0x0.
WARNING: OilBarrel (PROTO) > Shape > PBRAppearance > ImageTexture: Cannot load texture 'C:/Program Files/Webots/projects/objects/obstacles/protos/textures/oil_barrel_bottom_occlusion.jpg': Unsupported image format.
```

This bug was reported by several users (e.g. #326) and I was finally able to reproduce it by starting Webots from `cmd.exe`. It is working fine when launched from the desktop shortcut.

**Steps to Reproduce**
1. Launch Webots with `cmd.exe`

**Expected behavior**
The textures should load without any problem.

**Screenshots**
![capture](https://user-images.githubusercontent.com/2461619/51732085-62acbf80-207d-11e9-8076-d23f04c528ff.PNG)

**System**
 - Operating System: Windows 10 (only from cmd.exe)
 - `PATH` environmental variable from `cmd.exe`:
```
C:\Program Files\Python37\Scripts\;C:\Program Files\Python37\;C:\msys64\home\David\develop\webots-develop\webots\msys64\mingw64\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Windows Kits\10\Windows Performance Toolkit\;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\DLR\Sumo\bin\;C:\Program Files (x86)\DLR\Sumo\tools\;C:\Program Files\MATLAB\R2018a\bin;C:\Program Files\MATLAB\R2017a\runtime\win64;C:\Program Files\MATLAB\R2017a\bin;C:\WINDOWS\System32\OpenSSH\;C:\Program Files\dotnet\;C:\Program Files\Git LFS;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Python37\Scripts\;C:\Python37\;C:\msys64\home\David\develop\webots-develop\webots\msys64\mingw64\bin;C:\Users\David\AppData\Local\Microsoft\WindowsApps;C:\Users\David\AppData\Local\atom\bin;C:\Users\David\AppData\Local\Microsoft\WindowsApps;C:\Python27;C:\Program Files\Java\jdk1.8.0_121\bin;
```

**Comment by omichel** [comment] 2019-01-25 09:04
I could reproduce the problem as well, but I notice that it can be fixed by starting `webots.bat` instead of `webots.exe`. This is probably due to the fact the DOS cmd.exe ignores the `webots.exe.config` file that adds an extra path to the search for shared libraries (e.g., `../../usr/bin`).

**Comment by omichel** [comment] 2019-01-29 08:44
We should ask the users to launch `webots.bat` instead of `webots.exe` to see whether that fixes the problem for them.

**Closed** 2019-02-19 10:59 UTC
