### ISSUE TITLE
Hyperlinks no longer visible after clicking on it

### ISSUE THREAD

**Issue by stefaniapedrazzi** [omichel/webots#502] opened 2019-05-27 16:03 UTC
**Documentation page(s) concerned**
Any page containing an hyperlink

**What is the problem with the current documentation?**
Hyperlink text color is blue and they are visible in the text.
But after clicking on it, the color is changed to black and they are no longer visible.

**Describe how you would fix it**
Improve the color definition in the CSS.

**Comment by fabienrohrer** [comment] 2019-05-28 06:41
Just to be sure we agree on the description of this issue: this seems to occur only on hyperlink targeting an external link, and only once per page, right?
Internal links seems to behave correctly.

**Comment by stefaniapedrazzi** [comment] 2019-05-28 06:43
No, I get this issue with internal links: for example when in the reference manual with link to other node pages.
Note that it is not only the visited rule that changes the color to black but also the hover rule.

**Comment by stefaniapedrazzi** [comment] 2019-05-28 06:44
But after you click on the page and unselect the link, then it returns to the original link (non-visited) color, because it is the "active" rule that sets the text color to black.

**Comment by fabienrohrer** [comment] 2019-05-28 06:53
Ok. It seems that I can only reproduce the "hover" issue on the macOS browsers, and the "active" issue seems to only occur on external links in my environment.

**Comment by fabienrohrer** [comment] 2019-05-28 08:11
Fixed in #504

**Closed by fabienrohrer** 2019-05-28 08:11 UTC
Labels: enhancement
