### ISSUE TITLE
LED sensor Problem

### ISSUE THREAD

**Issue by ExcaliburKong** [omichel/webots#702] opened 2019-07-05 08:31 UTC
**Describe the Bug**
Everytime I was trying to add an LED sensor to my robot and edit the LED shape, webots would crash and quit.
**Steps to Reproduce**
1. Go to 'Robot'
2. Click on 'children'
3. Add an 'LED'
2. Click on 'LED's children'

**Expected behavior**
Hope I can add the LED sensor.

**Screenshots**
![QQ截图20190705155134](https://user-images.githubusercontent.com/52562524/60706798-d6140080-9f3c-11e9-8172-2e5d0cd63a0b.png)

**System**
 - Operating System: Windows 10
 - Graphics Card: NVIDIA GeForce GTX 1060  3GB

**Additional context**

**Comment by omichel** [comment] 2019-07-05 09:37
I cannot reproduce this crash. Could you tell me:
- which version of Webots are you using?
- which world file are you using?
- is the simulation running or paused?
- is your robot running some specific controller?
If you are using your own world file, please upload it.

**Comment by DavidMansolino** [comment] 2019-07-16 07:07
Since we can't reproduce the problem and have no feedback I will close this issue. Do not hesitate to give more precisions and we will re-open it.

**Closed by DavidMansolino** 2019-07-16 07:07 UTC
